config/routes.rb
Rails.application.routes.draw do
  resources :organizations
  resources :users
  resources :permissions

  resources :labs
  resources :courses

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/calendar_entry.rb
class CalendarEntry < ApplicationRecord
  belongs_to :schedule
  
  # cache only
  belongs_to :course
  belongs_to :lab

  def recreate_on_schedule
    schedule.ical
  end
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :organization
  belongs_to :user

  has_many :schedules

  def to_s
    name
  end
end

app/models/lab.rb
class Lab < ApplicationRecord
  has_many :schedules

  def to_s
    name
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  include DmUniboCommon::Organization

  has_many :permissions, class_name: "DmUniboCommon::Permission"

  has_many :courses
end

app/models/schedule.rb
# wrapper in db for ice_tea.
# on initializ and save updates start_time and end_time accordingly
class Schedule < ApplicationRecord
  belongs_to :course
  belongs_to :lab

  attr_accessor :ical                          # IceCube::Schedule
  serialize :ice_tea_sched_serialization, Hash # seralization attribute

  after_initialize :sync_with_icalendar,
                   :update_dates

  before_save :serialize_icecube,
              :update_dates

  def start_time
    self.ical.start_time
  end

  def end_time
    self.ical.end_time
  end

  attr_accessor :days
  serialize :days
  def self.weekdays
    Date::DAYNAMES.map { |d| d.upcase }
  end

  private

  # after initialize 
  # if we don't pass @ical we load it from serialization
  def sync_with_icalendar
    if (! @ical) && self.ice_tea_sched_serialization
      @ical = IceCube::Schedule.from_hash(self.ice_tea_sched_serialization)
    end
  end

  def serialize_icecube
    if @ical
      self.ice_tea_sched_serialization = @ical.to_hash
    end
  end

  def update_dates
    if @ical
      self.start_time = @ical.start_time
      self.end_time = @ical.end_time
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  include DmUniboCommon::User

  has_many :courses 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  after_action :verify_authorized, except: [:who_impersonate, :impersonate, :stop_impersonating]

  helper DmUniboCommon::Engine.helpers
  include DmUniboCommon::Controllers::Helpers
  include UserPermissionHelper # current_user, current_organization

  impersonates :user

  before_action :log_current_user, :set_locale, :set_organization, :retrive_authlevels # , :redirect_unsigned_user, :retrive_authlevels
  # before_action :log_current_user, :set_locale, :set_organization, :redirect_unsigned_user, :retrive_authlevels

  def set_locale
    I18n.locale = :it
  end

  # no security hidden. 
  # We set organization with params[:__org__] as organization_id in config/routes
  def set_organization
    session[:user_id] = User.find_by_upn('pietro.donatini@unibo.it').id
    if params[:__org__]
      session[:oid] = params[:__org__].to_i 
    end
    # fallback to default organization
    session[:oid] ||= 1

    @current_organization = Organization.find(session[:oid].to_i)
    if current_user
      current_user.current_organization = @current_organization
    end
  end

  def retrive_authlevels
    if current_user
      current_user.authorization = DmUniboCommon::Authorization.new(request.remote_ip, current_user)
    end
  end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :get_course_and_check_permission, only: [:show, :edit, :update, :destroy]

  def index
    @courses = current_user.current_organization.courses
    authorize @courses
  end

  def show 
    @course = Course.find(params[:id])
    authorize @course
  end

  def new
    @course = course.new
    authorize @course
  end

  def create
    @course = course.new(course_params)
    authorize @course
    if @course.save
      redirect_to courses_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @course.update(course_params)
      redirect_to courses_path
    else
      render :edit
    end
  end

  private

  def get_course_and_check_permission
    @course = Course.find(params[:id])
    authorize @course
  end

  def course_params
    params[:course].permit(:code, :name)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    skip_authorization
    month = (params[:m] || 1).to_i 
    @beginning_of_the_day = Date.new(2020, month, 1)
    @first_day_of_week = @beginning_of_the_day.wday
  end
end

app/controllers/labs_controller.rb
class LabsController < ApplicationController
  before_action :get_lab_and_check_permission, only: [:show, :edit, :update, :destroy]

  def index
    @labs = Lab.all
    authorize @labs
  end

  def show
  end

  def new
    @lab = Lab.new
    authorize @lab
  end

  def create
    @lab = Lab.new(lab_params)
    authorize @lab
    if @lab.save
      redirect_to labs_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @lab.update(lab_params)
      redirect_to labs_path
    else
      render :edit
    end
  end

  private

  def get_lab_and_check_permission
    @lab = Lab.find(params[:id])
    authorize @lab
  end

  def lab_params
    params[:lab].permit(:code, :name)
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @organizations = Organization.all
    authorize @organizations
  end

  def show
    @organization = Organization.find(params[:id])
    authorize @organization
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < DmUniboCommon::PermissionsController
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  def new
    @course = Course.find(params[:course_id])
    @lab    = Lab.find(params[:lab_id])
    @schedule = @course.schedules.new(lab: @lab)
    authorize @schedule
  end

  def create
    @course = Course.find(params[:schedule][:course_id])
    @lab    = Lab.find(params[:schedule][:lab_id])
    @schedule = @course.schedules.new(lab: @lab)
    raise @schedule.inspect
    authorize @schedule
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
    authorize @users
  end

  def new
    authorize :user
  end

  def create
    authorize :user
    if r = /\A(\w+\.\w+)(@unibo.it)?\z/.match(params[:upn])
      upn = r[1] + '@unibo.it'
      begin
        User.syncronize(upn)
      rescue DmUniboCommon::NoUser
        flash[:alert] = "Non esiste l'utente selezionato nel database di Ateneo."
      end
    end
    redirect_to new_user_path
  end
end

app/helpers/application_helper.rb
include DmUniboCommonHelper

module ApplicationHelper
end

app/helpers/lab_helper.rb
module LabHelper
end

app/helpers/user_permission_helper.rb
module UserPermissionHelper

  def current_organization
    @current_organization
  end

  # see app/policies/application_policy.rb
  def user_is_manager?
    current_user and current_user.authorization.can_manage?(current_organization)
  end

  def user_is_manager!
    user_is_manager? or raise DmUniboCommon::NoAccess
  end

  def redirect_home_with_error
    redirect_to root_path, alert: "Non avete diritti sufficienti per accedere alla pagina richiesta."
  end

end

app/views/courses/_course.html.erb
<%= dm_card title: course.name do %>  
  <dl class='dl-horizontal'>
    <dt>codice</dt>
    <dd><%= course.code %></dd>
    <dt>docente</dt>
    <dd><%= course.user %></dd>
    <dt>studenti</dt>
    <dd><%= course.student_number %></dd>
    <dt>totale ore</dt>
    <dd><%= course.hours %></dd>
  </dl> 

  <%= link_to_edit([:edit, course]) if policy(course).edit? %>  
<% end %>

app/views/courses/_form.html.erb
<%= dm_form_for @course, title: "Corso" do |lab| %>  
  <%= lab.input :code %>  
  <%= lab.input :name %>  
  <%= lab.input :hours %>  
  <%= lab.input :student_number %>  
  <%= lab.submit %>  
<% end %>

app/views/courses/edit.html.erb
<%= render 'form' %>

app/views/courses/index.html.erb
<h1><%= current_user.current_organization %></h1>

<div class="row">
  <% @courses.each do |course| %>  
    <div class="col-md-4">
      <%= render course %>  
    </div>
  <% end %>
</div>

app/views/courses/show.html.erb
<h1><%= @course %></h1>

di <%= @course.user %>  

app/views/home/index.html.erb
<%# monday is 1 %>  
<%= l @beginning_of_the_day %>  
<%= @first_day_of_week %>  
<div class="calendar">
	<div class="days-of-week">
		<div class="day-block">Monday</div>
		<div class="day-block">Tuesday</div>
		<div class="day-block">Wednesday</div>
		<div class="day-block">Thursday</div>
		<div class="day-block">Friday</div>
		<div class="day-block">Saturday</div>
		<div class="day-block">Sunday</div>
	</div>
	<div class="days-of-month">
    <% @first_day_of_week = 6 if @first_day_of_week == 0 %>  
    <% while @first_day_of_week > 1 %>  
      <div class="day-block">---</div>
      <% @first_day_of_week -= 1 %>  
    <% end %>

    <% (1..31).each do |d| %>  
      <div class="day-block">
        <div class="day-number">
          <%= d %>
        </div>
        pippo pluto e paperino
      </div>
    <% end %>
	</div>
</div>

app/views/labs/_form.html.erb
<div class="container">
  <%= dm_form_for @lab, title: "Lab" do |lab| %>  
    <%= lab.input :code %>  
    <%= lab.input :name %>  
    <%= lab.submit %>  
  <% end %>
</div>

app/views/labs/_lab.html.erb
<%= dm_card title: lab.name do %>  
  <dl class='dl-horizontal'>
    <dt>studenti</dt>
    <dd><%= lab.student_number %></dd>
  </dl> 

  <%= link_to_edit([:edit, lab]) if policy(lab).edit? %>  
<% end %>

app/views/labs/edit.html.erb
<%= render 'form' %>

app/views/labs/index.html.erb
<h1>LABS</h1>

<div class="row">
  <% @labs.each do |lab| %>  
    <div class="col-md-4">
      <%= render lab %>  
    </div>
  <% end %>
</div>

app/views/labs/new.html.erb
<%= render 'form' %>

app/views/labs/show.html.erb
<h1><%= @lab %> </h1>

app/views/layouts/_menu.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">  
  <%= link_to root_path, class: "navbar-brand text-info" do %>
    LabSched <%= current_user.current_organization.description %>  
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav ml-auto">
      <% if policy(:course).index? %>  
        <li class="nav-item"><%= link_to 'corsi', courses_path, class: 'nav-link' %></li>
      <% end %>
      <% if policy(:lab).index? %>  
        <li class="nav-item"><%= link_to 'labs', labs_path, class: 'nav-link' %></li>
      <% end %>
      <% if policy(:organization).index? %>  
        <li class="nav-item"><%= link_to 'organizations', organizations_path, class: 'nav-link' %></li>
      <% end %>
      <% if policy(:user).index? %>  
        <li class="nav-item"><%= link_to 'utenti', users_path, class: 'nav-link' %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="it">
  <head>
    <meta charset="utf-8">
    <title>LabSched</title>

    <meta name="viewport" content="width=device-width, minimum-scale=1.0, initial-scale=1.0, shrink-to-fit=no, user-scalable=yes"/>
    <meta name="description" content="LabSched"/>
    <meta property="og:description" content=""/>
    <meta name="keywords" content=""/>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render(partial: 'layouts/menu') unless @no_menu %>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/organizations/index.html.erb
<h1>Organizations</h1>

<div class="list-group">
  <% @organizations.each do |organization| %>  
    <%= link_to organization, organization, class: 'list-group-item list-group-item-action' %>
  <% end %>
</div>

app/views/organizations/show.html.erb
<h1><%= @organization %></h1>

<ul>
  <% @organization.courses.each do |course| %>  
    <li><%= link_to course, course %> </li>
  <% end %>
</ul>

app/views/schedules/new.html.erb
<h1><%= @course %></h1>

<h2><%= @lab %></h2>

<%= dm_form_for @schedule do |s| %>  
  <%= s.input :course_id, as: :hidden %>  
  <%= s.input :lab_id, as: :hidden %>  
  <%= s.input :start_time, as: :date_html5, label: 'Inizio'  %>  
  <%= s.input :end_time, as: :date_html5, label: 'Fine'  %>  
  <%= s.input :start_time, as: :time, minute_step: 15 %>  
  <%= s.input :end_time, as: :time, minute_step: 15 %>  

  <%= s.input :days, as: :check_boxes, collection: Schedule.weekdays %>  

  <%# <% Schedule.weekdays.each do |day| %1> %>
  <%#    <%= check_box :schedule, :days, { multiple: true }, day.downcase, nil %1> <%= day.downcase %1> %>
  <%# <% end %1> %>

  <%= s.submit %>  
<% end %> 

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @users.each do |user| %>  
    <li><%= user.cn %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>Aggiungi nuovo utente</h1>

<div style="text-align: center">
<%= form_tag users_path do %>  
  <p><%= text_field_tag :upn %> @unibo.it</p>
  <p><%= submit_tag("Crea") %></p>
<% end %>
</div>